### ISSUE TITLE
Altitude data and FOV information

### ISSUE THREAD

**Issue by rebeccasc** [AerVisLoc/vpair#2]
Hi, first of all great work generating all the data!

I would like to use the data for one of my student projects. But for this I need to know the altitude/height to each image as well as the field of view (FOV) of the used camera. I searched for it in the paper but did not find any information there. Is it possible to access this information?

Thanks in advance!

Rebecca

**Comment by AerVisLoc** [comment]
Hello Rebecca,

you can find the intrinsics of the camera in the camera calibration file. If you need more help calculating the fov from the intrinsics let me know. The altitude can be retrieved from poses.csv.
