### ISSUE TITLE
Full dataset download

### ISSUE THREAD

**Issue by joeylovepizza** [AerVisLoc/vpair#3]
Hello,

Thank you for your work!

I am currently working on a project about visual absolute localization, and I find the sample dataset in this repository to be very relevant to my work. I have filled out the form.  I'd appreciate it if you cound deal with my request.

Thank you again！

Suxing

**Comment by zhantian00** [comment]
Hi,
Thank you and your team for this work!

I find that the VPAIR dataset would greatly contribute to the advancement of my work. I have also filled out the form.

I would greatly appreciate it if you could provide any assistance or guidance regarding the status of my dataset request. If there are any additional steps I need to take or if there is a specific timeframe within which I can expect a response, please let me know.

Tian Zhan
