### ISSUE TITLE
Question about the pose data in poses.csv

### ISSUE THREAD

**Issue by euncheolChoi** [AerVisLoc/vpair#4]
Hello. Thank you for sharing this great dataset.  
I have a question about the Pose data. 
In the pose data provided, the altitude is distributed between 400 and 800 values. As far as I know, altitude is in meters, but looking at the provided pair images, it doesn't look like there is an altitude difference about 300 meters. 
Can you shed some light on this?

**Comment by michaelschleiss** [comment]
The values in poses.csv are altitude above mean see level (MSL). You would need to convert this information into your reference coordinate system of your choice. 

Are you looking for the distance to the surface?

**Comment by euncheolChoi** [comment]
Yes,  what I'm interested in is not the height from mean sea level, but the distance from the ground.
In this case, what is the distance from the groud?

Thanks in advance.

**Comment by michaelschleiss** [comment]
You can find the distance to the ground here:
- [distance_to_ground.csv](https://github.com/AerVisLoc/vpair/files/12337294/distance_to_ground.csv)

This information was retrieved using a Digital Elevation Model (DEM). Please note that a DEM is a bare earth model and therefore does not include man made or natural surface features (e.g. buildings, vegetation).
