### ISSUE TITLE
Rosbag file for VP-Air dataset

### ISSUE THREAD

**Issue by euncheolChoi** [AerVisLoc/vpair#6]
Thanks for sharing this great dataset. 
In the provided dataset, in the camera_calibration.yaml file, there is a rostopic: /cam_vo/image_raw.  
If the dataset was recorded via ROS, I was wondering if you could provide that rosbag file. 
Looking forward to your response, thank you.

![image](https://github.com/AerVisLoc/vpair/assets/86426437/f0b4544c-bbc4-4225-8a20-d6d7de2868e6)

**Comment by michaelschleiss** [comment]
At the moment I cannot share the rosbags. Sorry.

**Comment by euncheolChoi** [comment]
Oh I see, then do you have any plans to release rosbag later?
