### ISSUE TITLE
FoV information for the camera used

### ISSUE THREAD

**Issue by euncheolChoi** [AerVisLoc/vpair#7]
Thanks for sharing this great dataset. I am utilizing the VP-Air dataset for my personal project at school. In my project, I need the FoV value of the camera, but I couldn't find it in the camera_calibration.yaml file and in the paper. 

Therefore, I was wondering if you could share the FoV value of the camera. 
Thanks in advance.

**Comment by ganshanliushui678** [comment]
Its HFOV is 57 degree
![QQ截图20240110153324](https://github.com/AerVisLoc/vpair/assets/126451987/a5b8f477-89e5-43d0-a666-3bbd611c02e5)

**Comment by michaelschleiss** [comment]
Please refer to this  [issue](https://github.com/AerVisLoc/vpair/issues/8#issuecomment-2004188702)
