### ISSUE TITLE
More camera parameters

### ISSUE THREAD

**Issue by andriilitvynchuk** [AerVisLoc/vpair#8]
Hi! Thanks for your awesome work, I have one additional request: could please provide the sensor height and width + focal length of the camera? They are missing in camera calibration config

**Comment by michaelschleiss** [comment]
Here are some details about the camera:

Sensor: ON Semi KAI-02050
Sensor Type: CCD Progressive
Shutter Mode: Global shutter
Resolution: 1600 x 1200
Sensor Size: 2/3 inch
Pixel Size: 5.5 μm × 5.5 μm

Horizontal Field of View: 56.14 deg
Vertical Field of View: 43.60 deg
