### ISSUE TITLE
Origin of reference data

### ISSUE THREAD

**Issue by vnmsklnk** [AerVisLoc/vpair#9]
Hello, there is a question about the origin of the reference data. The paper states that reference images are orthophotos, but what is the origin of these images? Satellite or aerial?

**Comment by AerVisLoc** [comment]
The orthophotos were sourced from the state survey office in Nordrhein-Westphalia, Germany. Detailed information  on the orthophotos and how to access the orthophotos is available [here (in German)](https://www.bezreg-koeln.nrw.de/geobasis-nrw/produkte-und-dienste/luftbild-und-satellitenbildinformationen/aktuelle-luftbild-und-0). 

The orthophotos were processed by the state survey office using aerial surveys. The raw aerial images from which the orthophotos were created are not available publicly.

**Comment by vnmsklnk** [comment]
Thank you!
